#ifndef RT_ASSERT_H_
#define RT_ASSERT_H_

/* Assertion support for Simulix.
 *
 * A file with the same name may be generated by Matlab Coder.  This file
 * replaces it.
 */

#include "sx_assert.h"

#define utAssert(expr) sx_assert((expr), "Assertion " #expr " failed")

#endif
