#ifndef RT_ASSERT_H_
#define RT_ASSERT_H_

/* Assertion support for Simulix.
 *
 * A file with the same name may be generated by Matlab Coder.  This file
 * replaces it.
 */

extern void sx_assert_f(int cond, const char *file, int line, const char *msg);

#define sx_assert(expr, msg) sx_assert_f((expr), __FILE__, __LINE__, (msg))

#define utAssert(expr) sx_assert((expr), "Assertion " #expr " failed")

#endif
